### ISSUE TITLE
GPU out of memory error during VAK predict

### ISSUE THREAD

**Issue by SamuelBrudner** [vocalpy/vak#301]
I have successfully used VAK on several datasets, but recently I got a GPU out of memory error on two different datasets. I tried reducing the batch size in the predict.toml file, but this did not solve the problem. In addition, the program runs for several hours before crashing (these are very large datasets coming from a complete developmental trajectories of juvenile birds). That leads me to think something is accumulating in the GPU across files without being successfully cleared.
Here is the output from the crash:

batch 101431 / 165217:  61%|███████████████████████████████████████▎                        | 101432/165217 [7:11:40<4:31:27,  3.92it/s]
Traceback (most recent call last):
  File "/home/mooney_lab/anaconda3/envs/VAK/bin/vak", line 8, in <module>
    sys.exit(main())
  File "/home/mooney_lab/anaconda3/envs/VAK/lib/python3.6/site-packages/vak/__main__.py", line 44, in main
    config_file=args.configfile)
  File "/home/mooney_lab/anaconda3/envs/VAK/lib/python3.6/site-packages/vak/cli/cli.py", line 28, in cli
    predict(toml_path=config_file)
  File "/home/mooney_lab/anaconda3/envs/VAK/lib/python3.6/site-packages/vak/cli/predict.py", line 54, in predict
    logger=logger)
  File "/home/mooney_lab/anaconda3/envs/VAK/lib/python3.6/site-packages/vak/core/predict.py", line 181, in predict
    device=device)
  File "/home/mooney_lab/anaconda3/envs/VAK/lib/python3.6/site-packages/vak/engine/model.py", line 435, in predict
    return self._predict(pred_data)
  File "/home/mooney_lab/anaconda3/envs/VAK/lib/python3.6/site-packages/vak/engine/model.py", line 309, in _predict
    y_pred = self.network.forward(x)
  File "/home/mooney_lab/anaconda3/envs/VAK/lib/python3.6/site-packages/tweetynet/network.py", line 144, in forward
    features = self.cnn(x)
  File "/home/mooney_lab/anaconda3/envs/VAK/lib/python3.6/site-packages/torch/nn/modules/module.py", line 550, in __call__
    result = self.forward(*input, **kwargs)
  File "/home/mooney_lab/anaconda3/envs/VAK/lib/python3.6/site-packages/torch/nn/modules/container.py", line 100, in forward
    input = module(input)
  File "/home/mooney_lab/anaconda3/envs/VAK/lib/python3.6/site-packages/torch/nn/modules/module.py", line 550, in __call__
    result = self.forward(*input, **kwargs)
  File "/home/mooney_lab/anaconda3/envs/VAK/lib/python3.6/site-packages/tweetynet/network.py", line 56, in forward
    groups=self.groups,
RuntimeError: CUDA out of memory. Tried to allocate 686.00 MiB (GPU 0; 11.90 GiB total capacity; 9.97 GiB already allocated; 108.38 MiB free; 10.70 GiB reserved in total by PyTorch)

**Comment by NickleDave** [comment]
Hi @SamuelBrudner 

Just replied to your email.
Thank you for the detailed error report. 
If it's okay with you I'd like to post some of those additional helpful details here, in case other people run into similar problems.
And just to try and keep discussion of issues on GitHub.

But for now just to make sure you see my reply:

> Long story short, this makes me think that it **is** possible that one of the files is big enough to cause an OOM error.
> 
> Can you try the following?Can you use pandas to sort the csv rows by decreasing duration, save this as a new csv, run predict on that new csv, and see if it crashes immediately?If so, that would give us some positive evidence that a long file is the source of the problem.You want to do something like this:
> import pandas as pddf = pd.read_csv('032312_prep_210206_103340.csv')df_sorted = df.sort_values(by='duration', ascending=False)df_sorted.to_csv('tmp_032312_prep_210206_103340.csv')And then make a temporary copy of your config and point `csv_path` at the `tmp` version of the dataset .csv

**Comment by NickleDave** [comment]
Going to close this as stale
