### ISSUE TITLE
"[WinError 1455]: The paging file too small" when running `vak prep`

### ISSUE THREAD

**Issue by marichard123** [vocalpy/vak#381]
The following error is encountered when running the prep step on the training file with vak on Windows, following the standard directions without modification. However, following the steps given in https://github.com/NickleDave/vak/issues/293#issuecomment-773795218 mitigates the issue. The error traceback:

```python
(vak-env) PS C:\Users\Richard\documents> vak prep gy6or6_train.toml
determined that purpose of config file is: train
will add 'csv_path' option to 'TRAIN' section
purpose for dataset: train
will split dataset
making array files containing spectrograms from audio files in: C:\Users\Richard\Documents\Fall_2021\Bat_Stuff\TweetynetPipeline
creating array files with spectrograms
[                                        ] | 0% Completed |  6.6s
Traceback (most recent call last):
  File "c:\users\richard\anaconda3\envs\vak-env\lib\runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "c:\users\richard\anaconda3\envs\vak-env\lib\runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "C:\Users\Richard\Anaconda3\envs\vak-env\Scripts\vak.exe\__main__.py", line 7, in <module>
  File "c:\users\richard\anaconda3\envs\vak-env\lib\site-packages\vak\__main__.py", line 45, in main
    cli.cli(command=args.command, config_file=args.configfile)
  File "c:\users\richard\anaconda3\envs\vak-env\lib\site-packages\vak\cli\cli.py", line 30, in cli
    COMMAND_FUNCTION_MAP[command](toml_path=config_file)
  File "c:\users\richard\anaconda3\envs\vak-env\lib\site-packages\vak\cli\prep.py", line 146, in prep
    logger=logger,
  File "c:\users\richard\anaconda3\envs\vak-env\lib\site-packages\vak\core\prep.py", line 214, in prep
    logger=logger,
  File "c:\users\richard\anaconda3\envs\vak-env\lib\site-packages\vak\io\dataframe.py", line 139, in from_files
    labelset=labelset,
  File "c:\users\richard\anaconda3\envs\vak-env\lib\site-packages\vak\io\audio.py", line 234, in to_spect
    spect_files = list(bag.map(_spect_file))
  File "c:\users\richard\anaconda3\envs\vak-env\lib\site-packages\dask\bag\core.py", line 1451, in __iter__
    return iter(self.compute())
  File "c:\users\richard\anaconda3\envs\vak-env\lib\site-packages\dask\base.py", line 283, in compute
    (result,) = compute(self, traverse=False, **kwargs)
  File "c:\users\richard\anaconda3\envs\vak-env\lib\site-packages\dask\base.py", line 565, in compute
    results = schedule(dsk, keys, **kwargs)
  File "c:\users\richard\anaconda3\envs\vak-env\lib\site-packages\dask\multiprocessing.py", line 230, in get
    **kwargs
  File "c:\users\richard\anaconda3\envs\vak-env\lib\site-packages\dask\local.py", line 487, in get_async
    raise_exception(exc, tb)
  File "c:\users\richard\anaconda3\envs\vak-env\lib\site-packages\dask\local.py", line 317, in reraise
    raise exc
  File "c:\users\richard\anaconda3\envs\vak-env\lib\site-packages\dask\local.py", line 221, in execute_task
    task, data = loads(task_info)
  File "c:\users\richard\anaconda3\envs\vak-env\lib\site-packages\vak\__init__.py", line 13, in <module>
    from . import (
  File "c:\users\richard\anaconda3\envs\vak-env\lib\site-packages\vak\cli\__init__.py", line 4, in <module>
    from . import cli, eval, learncurve, predict, prep, train
  File "c:\users\richard\anaconda3\envs\vak-env\lib\site-packages\vak\cli\cli.py", line 1, in <module>
    from .eval import eval
  File "c:\users\richard\anaconda3\envs\vak-env\lib\site-packages\vak\cli\eval.py", line 4, in <module>
    from .. import config
  File "c:\users\richard\anaconda3\envs\vak-env\lib\site-packages\vak\config\__init__.py", line 2, in <module>
    from . import (
  File "c:\users\richard\anaconda3\envs\vak-env\lib\site-packages\vak\config\config.py", line 5, in <module>
    from .eval import EvalConfig
  File "c:\users\richard\anaconda3\envs\vak-env\lib\site-packages\vak\config\eval.py", line 6, in <module>
    from .validators import is_a_directory, is_a_file, is_valid_model_name
  File "c:\users\richard\anaconda3\envs\vak-env\lib\site-packages\vak\config\validators.py", line 7, in <module>
    from .. import models
  File "c:\users\richard\anaconda3\envs\vak-env\lib\site-packages\vak\models\__init__.py", line 2, in <module>
    from . import teenytweetynet
  File "c:\users\richard\anaconda3\envs\vak-env\lib\site-packages\vak\models\teenytweetynet.py", line 1, in <module>
    import torch
  File "c:\users\richard\anaconda3\envs\vak-env\lib\site-packages\torch\__init__.py", line 124, in <module>
    raise err
OSError: [WinError 1455] The paging file is too small for this operation to complete.
```

**Comment by NickleDave** [comment]
Thank you @marichard123 for taking time to post this here.

In case anyone runs into a similar issue but misses the link in your post:
seems like creating a `conda` environment and installing `vak` into it as described here can resolve this issue

https://github.com/NickleDave/vak/issues/293#issuecomment-773795218
```
C:\You> conda create -n vak-env python==3.8
C:\You> conda activate vak-env
(vak-env) C:\You> pip install torch===1.7.1 torchvision===0.8.2 -f https://download.pytorch.org/whl/torch_stable.html
(vak-env) C:\You> pip install vak==0.4.0.dev1
(vak-env) C:\You> pip install tweetynet
```

The long term fix is to make a `conda` package e.g. on conda-forge as in #70 so users have this install option.
This issue and the related #293 should be closed after that is resolved

**Comment by NickleDave** [comment]
Closing this as stale.  There is now a conda-forge package and I think that may mitigate some of these issues?
