### ISSUE TITLE
ENH: better handle the case when `labelset` is not specified in config file

### ISSUE THREAD

**Issue by NickleDave** [vocalpy/vak#468]
Currently if one runs `vak prep` for a train config without a `labelset` option specified, it will create and validate the spectrograms, but then crash when creating the target duration splits -- see traceback below

- [x] We should at a bare minimum raise an error before running `prep` if no labelset is specified, for any command that requires them -- i.e. anything that is not 'predict'
- [ ] Extra-fancy behavior would be to assume that, if no labelset is specified, then all labels in `data_dir` should go into `labelset`, i.e. to create it dynamically
  - Need to think about whether this would have any downstream ramifications. 
  - We would need to add the programatically-computed labelset to the config file
 
```
$ vak prep data/configs/gy6or6_train.toml 
determined that purpose of config file is: train
will add 'csv_path' option to 'TRAIN' section
purpose for dataset: train
will split dataset
making array files containing spectrograms from audio files in: /home/bart/Documents/data/birdsong/BFSongRepository/gy6or6/032212/has_notmat
creating array files with spectrograms
[########################################] | 100% Completed |  5.9s
creating dataset from spectrogram files in: data/prep/spectrograms_generated_220315_120837
validating set of spectrogram files
[########################################] | 100% Completed |  3.7s
creating pandas.DataFrame representing dataset from spectrogram files
[########################################] | 100% Completed |  3.2s
Total target duration of splits: 65.0 seconds. Will be drawn from dataset with total duration: 2362.778.
Traceback (most recent call last):
  File "/home/bart/anaconda3/envs/vak-tweetynet-tutorial/bin/vak", line 10, in <module>
    sys.exit(main())
  File "/home/bart/anaconda3/envs/vak-tweetynet-tutorial/lib/python3.9/site-packages/vak/__main__.py", line 45, in main
    cli.cli(command=args.command, config_file=args.configfile)
  File "/home/bart/anaconda3/envs/vak-tweetynet-tutorial/lib/python3.9/site-packages/vak/cli/cli.py", line 30, in cli
    COMMAND_FUNCTION_MAP[command](toml_path=config_file)
  File "/home/bart/anaconda3/envs/vak-tweetynet-tutorial/lib/python3.9/site-packages/vak/cli/prep.py", line 132, in prep
    vak_df, csv_path = core.prep(
  File "/home/bart/anaconda3/envs/vak-tweetynet-tutorial/lib/python3.9/site-packages/vak/core/prep.py", line 220, in prep
    vak_df = split.dataframe(
  File "/home/bart/anaconda3/envs/vak-tweetynet-tutorial/lib/python3.9/site-packages/vak/split/split.py", line 141, in dataframe
    train_inds, val_inds, test_inds = train_test_dur_split_inds(
  File "/home/bart/anaconda3/envs/vak-tweetynet-tutorial/lib/python3.9/site-packages/vak/split/split.py", line 86, in train_test_dur_split_inds
    train_inds, val_inds, test_inds = brute_force(
  File "/home/bart/anaconda3/envs/vak-tweetynet-tutorial/lib/python3.9/site-packages/vak/split/algorithms/bruteforce.py", line 96, in brute_force
    for label_from_labelset in sorted(labelset):
TypeError: 'NoneType' object is not iterable
```

**Comment by NickleDave** [comment]
Fixing this but not adding "extra-fancy behavior" for now

Note that we will need to re-factor when we start using other models e.g. to train as unsupervised. Will figure it out then
