### ISSUE TITLE
BUG: main `core` and `cli` functions should check whether `csv_path` is None / exists (except for `prep`)

### ISSUE THREAD

**Issue by NickleDave** [vocalpy/vak#469]
running `vak eval` with a config file that has no `csv_path` option in the `EVAL` section produces the following:
```
Logging results to results/gy6or6_eval
loading spect scaler from path: results/gy6or6_train/results_220315_122127/StandardizeSpect
loading labelmap from path: results/gy6or6_train/results_220315_122127/labelmap.json
creating dataset for evaluation from: None
Traceback (most recent call last):
  File "/home/bart/anaconda3/envs/vak-tweetynet-tutorial/bin/vak", line 10, in <module>
    sys.exit(main())
  File "/home/bart/anaconda3/envs/vak-tweetynet-tutorial/lib/python3.9/site-packages/vak/__main__.py", line 45, in main
    cli.cli(command=args.command, config_file=args.configfile)
  File "/home/bart/anaconda3/envs/vak-tweetynet-tutorial/lib/python3.9/site-packages/vak/cli/cli.py", line 30, in cli
    COMMAND_FUNCTION_MAP[command](toml_path=config_file)
  File "/home/bart/anaconda3/envs/vak-tweetynet-tutorial/lib/python3.9/site-packages/vak/cli/eval.py", line 42, in eval
    core.eval(
  File "/home/bart/anaconda3/envs/vak-tweetynet-tutorial/lib/python3.9/site-packages/vak/core/eval.py", line 115, in eval
    val_dataset = VocalDataset.from_csv(
  File "/home/bart/anaconda3/envs/vak-tweetynet-tutorial/lib/python3.9/site-packages/vak/datasets/vocal_dataset.py", line 142, in from_csv
    df = pd.read_csv(csv_path)
  File "/home/bart/anaconda3/envs/vak-tweetynet-tutorial/lib/python3.9/site-packages/pandas/util/_decorators.py", line 311, in wrapper
    return func(*args, **kwargs)
  File "/home/bart/anaconda3/envs/vak-tweetynet-tutorial/lib/python3.9/site-packages/pandas/io/parsers/readers.py", line 680, in read_csv
    return _read(filepath_or_buffer, kwds)
  File "/home/bart/anaconda3/envs/vak-tweetynet-tutorial/lib/python3.9/site-packages/pandas/io/parsers/readers.py", line 575, in _read
    parser = TextFileReader(filepath_or_buffer, **kwds)
  File "/home/bart/anaconda3/envs/vak-tweetynet-tutorial/lib/python3.9/site-packages/pandas/io/parsers/readers.py", line 933, in __init__
    self._engine = self._make_engine(f, self.engine)
  File "/home/bart/anaconda3/envs/vak-tweetynet-tutorial/lib/python3.9/site-packages/pandas/io/parsers/readers.py", line 1217, in _make_engine
    self.handles = get_handle(  # type: ignore[call-overload]
  File "/home/bart/anaconda3/envs/vak-tweetynet-tutorial/lib/python3.9/site-packages/pandas/io/common.py", line 670, in get_handle
    ioargs = _get_filepath_or_buffer(
  File "/home/bart/anaconda3/envs/vak-tweetynet-tutorial/lib/python3.9/site-packages/pandas/io/common.py", line 427, in _get_filepath_or_buffer
    raise ValueError(msg)
ValueError: Invalid file path or buffer object type: <class 'NoneType'>
```

**Comment by NickleDave** [comment]
After looking at this more, I realized that all the core functions with the exception of `prep` should do this.  
Where "this" = "validate that csv_path exists".  
Similarly, the cli functions should check if `labelset` is None and raise a polite FileNotFoundError suggesting that a user run `prep` first.
Adding this now
