### ISSUE TITLE
ENH: Make `vak.files.spect.find_audio_fname` and `vak.files.files.find_fname` handle spaces

### ISSUE THREAD

**Issue by yardencsGitHub** [vocalpy/vak#589]
**Is your feature request related to a problem? Please describe.**
Folder names that include spaces are fine in the 'prep' and 'train' steps but cause a problem when the 'predict' tries to create the outputs annotation file.

The cause of the problem is
https://github.com/vocalpy/vak/blob/aa255281811db72de7faab8f9654e74584281ac4/src/vak/files/files.py#L27
where the regular expression "[\S]*{ext}" uses allows all strings without spaces.

**Describe the solution you'd like**
It would be nice to allow spaces in folder names.
For example, changing the above to "[\S\s]*{ext}"

**Describe alternatives you've considered**
An alternative is, obviously, to avoid spaces in folder names.
But this is not documented (I think) in the docs.
It is also nagging for users to get a crash over such a mundane issue.

**Additional context**
Monkeying the files.py to "[\S\s]*{ext}" works.
@NickleDave, I can open a PR but this is so small that perhaps it is better

**Comment by NickleDave** [comment]
Hi @yardencsGitHub can you attach an example config file where you have specified spaces in the path that cause this error, and the exact traceback you get?

It would help if you could paste in a list of your filenames with absolute paths, too.

I'm not sure I understand the source of the error.  
I'm guessing it's cause by
https://github.com/vocalpy/vak/blob/5c446fd8f71319a758de700c6b9f23365409f970/src/vak/core/predict.py#L241

**Comment by NickleDave** [comment]
Thank you @yardencsGitHub 

Can you do one more thing for me and paste in the full traceback you get?  
That would help me pin down what's going on the fastest

**Comment by yardencsGitHub** [comment]
Sure. See below.
This is solved, as I mentioned, if we allow spaces in:
https://github.com/vocalpy/vak/blob/aa255281811db72de7faab8f9654e74584281ac4/src/vak/files/files.py#L27
I tested it.

Traceback (most recent call last):
  File "/home/yardenc/miniconda3/envs/tweety-env/bin/vak", line 10, in <module>
    sys.exit(main())
  File "/home/yardenc/miniconda3/envs/tweety-env/lib/python3.8/site-packages/vak/__main__.py", line 45, in main
    cli.cli(commandTraceback (most recent call last):
  File "/home/yardenc/miniconda3/envs/tweety-env/bin/vak", line 10, in <module>
    sys.exit(main())
  File "/home/yardenc/miniconda3/envs/tweety-env/lib/python3.8/site-packages/vak/__main__.py", line 45, in main
    cli.cli(command=args.command, config_file=args.configfile)
  File "/home/yardenc/miniconda3/envs/tweety-env/lib/python3.8/site-packages/vak/cli/cli.py", line 30, in cli
    COMMAND_FUNCTION_MAP[command](toml_path=config_file)
  File "/home/yardenc/miniconda3/envs/tweety-env/lib/python3.8/site-packages/vak/cli/predict.py", line 42, in predict
    core.predict(
  File "/home/yardenc/miniconda3/envs/tweety-env/lib/python3.8/site-packages/vak/core/predict.py", line 230, in predict
    audio_fname = files.spect.find_audio_fname(spect_path)
  File "/home/yardenc/miniconda3/envs/tweety-env/lib/python3.8/site-packages/vak/files/spect.py", line 58, in find_audio_fname
    raise ValueError(
ValueError: unable to determine filename of audio file from: /media/yardenc/New Volume/YardenBirds/BF/gy6or6/032312_predict/spectrograms_generated_221115_191033/gy6or6_baseline_230312_0808.138.wav.spect.npz=args.command, config_file=args.configfile)
  File "/home/yardenc/miniconda3/envs/tweety-env/lib/python3.8/site-packages/vak/cli/cli.py", line 30, in cli
    COMMAND_FUNCTION_MAP[command](toml_path=config_file)
  File "/home/yardenc/miniconda3/envs/tweety-env/lib/python3.8/site-packages/vak/cli/predict.py", line 42, in predict
    core.predict(
  File "/home/yardenc/miniconda3/envs/tweety-env/lib/python3.8/site-packages/vak/core/predict.py", line 230, in predict
    audio_fname = files.spect.find_audio_fname(spect_path)
  File "/home/yardenc/miniconda3/envs/tweety-env/lib/python3.8/site-packages/vak/files/spect.py", line 58, in find_audio_fname
    raise ValueError(
ValueError: unable to determine filename of audio file from: /media/yardenc/New Volume/YardenBirds/BF/gy6or6/032312_predict/spectrograms_generated_221115_191033/gy6or6_baseline_230312_0808.138.wav.spect.npz

**Comment by NickleDave** [comment]
I think we want to do the following:
- [ ] just add a space to the pattern `[\S]` we use with the `re` in `find_fnames`. We don't want to use `[\S\s]` since that matches *all* whitespace characters including things like line returns, which might have some unintended consequences
- [ ] Inside `vak.files.spect.find_audio_fname` we should convert the input filename to a `pathlib.Path` and then only pass its `name` attribute to `find_fname`, so that a space in some part of the parent path won't matter to us anyway
- [ ] write additional unit tests to make sure that both of these fixes work as intended. Right now we only test with paths without spaces in them
