### ISSUE TITLE
Error when running vak prep train.toml

### ISSUE THREAD

**Issue by harshidapancholi** [vocalpy/vak#739]
Hi, I'm trying to install and run vak on a CPU computer (it runs perfectly fine on the GPU), and running into this error. Any ideas how to fix it?
(vak-env) F:\2pOptoInVivo\220810_R673-GCaMP\Song_analysis\Motif_3syll_analysis\TweetyNet_training>vak prep R673_train.toml
Traceback (most recent call last):
  File "C:\Users\Roberts Lab - HP\anaconda3\envs\vak-env\lib\runpy.py", line 197, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "C:\Users\Roberts Lab - HP\anaconda3\envs\vak-env\lib\runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "C:\Users\Roberts Lab - HP\anaconda3\envs\vak-env\Scripts\vak.exe\__main__.py", line 7, in <module>
  File "C:\Users\Roberts Lab - HP\anaconda3\envs\vak-env\lib\site-packages\vak\__main__.py", line 48, in main
    cli.cli(command=args.command, config_file=args.configfile)
  File "C:\Users\Roberts Lab - HP\anaconda3\envs\vak-env\lib\site-packages\vak\cli\cli.py", line 49, in cli
    COMMAND_FUNCTION_MAP[command](toml_path=config_file)
  File "C:\Users\Roberts Lab - HP\anaconda3\envs\vak-env\lib\site-packages\vak\cli\cli.py", line 23, in prep
    prep(toml_path=toml_path)
  File "C:\Users\Roberts Lab - HP\anaconda3\envs\vak-env\lib\site-packages\vak\cli\prep.py", line 99, in prep
    cfg = config.parse.from_toml_path(toml_path, sections=SECTIONS_PREP_SHOULD_PARSE)
  File "C:\Users\Roberts Lab - HP\anaconda3\envs\vak-env\lib\site-packages\vak\config\parse.py", line 200, in from_toml_path
    return from_toml(config_toml, toml_path, sections)
  File "C:\Users\Roberts Lab - HP\anaconda3\envs\vak-env\lib\site-packages\vak\config\parse.py", line 149, in from_toml
    are_options_valid(config_toml, section_name, toml_path)
  File "C:\Users\Roberts Lab - HP\anaconda3\envs\vak-env\lib\site-packages\vak\config\validators.py", line 121, in are_options_valid
    raise ValueError(err_msg)
ValueError: the following options from PREP section in the config file 'R673_train.toml' are not valid:
{'input_type', 'dataset_type'}

**Comment by NickleDave** [comment]
Hi @harshidapancholi my guess is that you have vak version 0.8.2 installed but the config file you are working with comes from the docs, that are for version 1.0.0a3.

What do you get if you run the python REPL in the terminal and enter the following?
```python
>>> import vak
>>> print(vak.__version__)
```

If it's anything less than 1.0.0a3 then you want to install the newest version directly.
`pip install vak==1.0.0a3`
(There's not a package for it on conda-forge yet so you need to `pip install`.)

Please let me know if that helps

**Comment by harshidapancholi** [comment]
Ok the version was 0.8.2. The version on which everything works is 1.0.a3 so you're right about the problem, but this exact same thing worked two weeks ago - just confused..

**Comment by NickleDave** [comment]
No worries!  
There's too many ways to install things in Python.  

Were you able to install 1.0.0a3 and get it to work?

**Comment by harshidapancholi** [comment]
Yes it did! Weird - it downgraded it at some point?

**Comment by NickleDave** [comment]
> Weird - it downgraded it at some point?

AFAIK Python packages shouldn't downgrade on their own.  
Might be you have more than one environment or something like that?  
(I know I do :confused: )

> Yes it did!

:raised_hands: great! glad to hear it
